import type { Recipe } from "./types";

// Placeholder data for building the workspace UI before the parser/API exist.
export const sampleRecipe: Recipe = {
  title: "Chicken Fajitas",
  sourceUrl: null,
  servings: 4,
  time: { prepMin: 15, cookMin: 20, totalMin: 35 },
  ingredients: [
    {
      id: "chicken",
      quantity: 1,
      unit: "lb",
      item: "chicken breast",
      prep: "sliced into strips",
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "1 lb chicken breast, sliced into strips",
    },
    {
      id: "onion",
      quantity: 1,
      unit: null,
      item: "onion",
      prep: "sliced",
      optional: false,
      size: "medium",
      substitutedFrom: null,
      originalText: "1 medium onion, sliced",
    },
    {
      id: "bell-peppers",
      quantity: 2,
      unit: null,
      item: "bell peppers",
      prep: "sliced",
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "2 bell peppers, sliced",
    },
    {
      id: "olive-oil",
      quantity: 2,
      unit: "tbsp",
      item: "olive oil",
      prep: null,
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "2 tbsp olive oil",
    },
    {
      id: "chili-powder",
      quantity: 1,
      unit: "tbsp",
      item: "chili powder",
      prep: null,
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "1 tbsp chili powder",
    },
    {
      id: "cumin",
      quantity: 1,
      unit: "tsp",
      item: "cumin",
      prep: null,
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "1 tsp cumin",
    },
    {
      id: "salt",
      quantity: 0.5,
      unit: "tsp",
      item: "salt",
      prep: null,
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "1/2 tsp salt",
    },
    {
      id: "tortillas",
      quantity: 8,
      unit: null,
      item: "flour tortillas",
      prep: null,
      optional: false,
      size: null,
      substitutedFrom: null,
      originalText: "8 flour tortillas",
    },
    {
      id: "lime",
      quantity: 1,
      unit: null,
      item: "lime",
      prep: "juiced",
      optional: true,
      size: null,
      substitutedFrom: null,
      originalText: "1 lime, juiced",
    },
  ],
  steps: [
    {
      id: "step-1",
      text: "In a bowl, toss the chicken strips with olive oil, chili powder, cumin, and salt.",
      ingredientRefs: ["chicken", "olive-oil", "chili-powder", "cumin", "salt"],
    },
    {
      id: "step-2",
      text: "Heat a large skillet over medium-high heat. Add the chicken and cook until browned, about 6-8 minutes.",
      ingredientRefs: ["chicken"],
    },
    {
      id: "step-3",
      text: "Add the onion and bell peppers to the skillet. Cook until softened, about 5-7 minutes.",
      ingredientRefs: ["onion", "bell-peppers"],
    },
    {
      id: "step-4",
      text: "Squeeze lime juice over the mixture and toss to combine.",
      ingredientRefs: ["lime"],
    },
    {
      id: "step-5",
      text: "Warm the tortillas and serve the chicken and vegetable mixture alongside them.",
      ingredientRefs: ["tortillas"],
    },
  ],
  equipment: ["large skillet"],
  notes: [],
};
